name: blj_search
description: Binary search, Linear search, and Jump search algorithms for finding elements in lists.
version: 1.0.1
repository: https://github.com/khusantoy/blj-search
homepage: https://github.com/khusantoy/blj-search
license: MIT

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
